version: '3'
services: 
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - CHOKIDAR_USEPOLLING=true      
    ports:
      - "3000:3000"
    volumes: 
      - /home/node/app/node_modules
      - .:/home/node/app
    stdin_open: true
  tests: 
    build: 
      context: .
      dockerfile: Dockerfile.dev
    command: ["npm", "run", "tests"]
    volumes: 
      - /home/node/app/node_modules
      - .:/home/node/app
    stdin_open: true    